### ISSUE TITLE
MediaPlayer.dll Case sensitivity

### ISSUE THREAD

**Issue by sl2365** [i2002/RainmeterMediaPlayer#3]
Hi,
Thanks for the plugin. I posted some feedback on the Rainmeter forum to inform you of the issue that seems to affect the ability to see Meters or Measures in Rainmeter skins.
See here for more info...
https://forum.rainmeter.net/viewtopic.php?p=217023#p217018

**Comment by i2002** [comment]
Hi,
Thank you for pointing this out.
Fixed in v1.3, now measure options are case insensitive.

**Comment by sl2365** [comment]
Much appreciated ;)
